### ISSUE TITLE
Ingress is not picking IP of LB

### ISSUE THREAD

**Issue by herveleclerc** [mariusmagureanu/vingress#3]
I've deployed vingress with these values
```yaml
service:
  type: LoadBalancer
  port: 80
  targetPort: 6081
  ```
  
 I'm on MS Azure
 
 I got this 
 ```bash
 kubectl get svc
NAME                      TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)             AGE
varnish-ingress-service   LoadBalancer   10.0.183.165   74.241.235.196   80:30220/TCP        17h
```

Here is the ingress definition

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    kubernetes.io/ingress: varnish
  name: podinfo-ing
  namespace: varnish-ingress
spec:
  ingressClassName: varnish
  rules:
  - host: podinfo.vcl.caas.fr
    http:
      paths:
      - backend:
          service:
            name: podinfo
            port:
              number: 9898
        path: /
        pathType: Prefix
        
```

```bash
kubectl get ingress
NAME          CLASS     HOSTS                 ADDRESS   PORTS   AGE
podinfo-ing   varnish   podinfo.vcl.caas.fr             80      6m14s
```

```bash
k describe ingress podinfo-ing
Name:             podinfo-ing
Labels:           kubernetes.io/ingress=varnish
Namespace:        varnish-ingress
Address:
Ingress Class:    varnish
Default backend:  <default>
Rules:
  Host                 Path  Backends
  ----                 ----  --------
  podinfo.vcl.caas.fr
                       /   podinfo:9898 (10.224.3.232:9898,10.224.4.159:9898)
Annotations:           <none>
Events:                <none>
```

**Comment by mariusmagureanu** [comment]
Hi @herveleclerc,

Thank you for reporting this, really appreciate the detailed description.

In full honesty, I have not tested the LoadBalancer service type just yet, so I need to look into it.
In the meantime, do requests against `podinfo.vcl.caas.fr` work as expected? Asking this as I see there is an external ip assigned.

**Comment by herveleclerc** [comment]
Hi, 

Yes it work as expected. 
It's just that,  the status of loadbalancer ip in ingress is not set. 

```yaml 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    kubernetes.io/ingress: varnish
  name: podinfo-ing
  namespace: varnish-ingress
  resourceVersion: "235814868"
  uid: 5ef445a2-9c06-4272-aed7-e625daec5060
spec:
  ingressClassName: varnish
  rules:
  - host: podinfo.vcl.caas.fr
    http:
      paths:
      - backend:
          service:
            name: podinfo
            port:
              number: 9898
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
  
```
  
  it should be like this 

```yaml
  status:
    loadBalancer:
      ingress:
      - ip: 74.241.235.196
```
